### ISSUE TITLE
JIT in WP editor

### ISSUE THREAD

**Issue by chicharitomagnetico** [jeffreyvr/tailpress#17]
Is there a way to use JIT in the WP editor?
I can't make it work.

**Comment by jeffreyvr** [comment]
I'm not sure if I know what you mean. If you mean that you would like to use the utility classes within the block editor, those will not be picked up since they are not in the template files. You could add those classes to the safelist.txt file.

If you mean something else, maybe you can explain some more about what you are trying to achieve.

**Comment by chicharitomagnetico** [comment]
Sure, I will explain a little more.
I built a few Gutenberg blocks. if I don't use JIT the blocks look almost like on the frontend side, (I couldn't manage to make the fonts work.)
When I activate JIT the blocks stop looking ok.
I guess I can resolve this by importing the final CSS to the editor-style.css

**Comment by jeffreyvr** [comment]
I don't have a solution for you other then maybe what you described yourself. Please share if you find out a nice way to go about this! :)
