### ISSUE TITLE
composer not firing

### ISSUE THREAD

**Issue by ianhobbs** [jeffreyvr/tailpress#52]
Am I missing a step?
After install running the install and  ran the command and got nothing.

"tailpress new example-theme" 

What are the enviro requirements?

Thanks

**Comment by ianhobbs** [comment]
Ok sorted it using the **regular** method.

**Comment by jeffreyvr** [comment]
Probably because of this:

https://stackoverflow.com/questions/26376516/laravel-php-command-not-found

**Comment by rowphant** [comment]
> Ok sorted it using the **regular** method.

What is the "regular" method?

I just want to set up a "package" like tailpress and finally have to google for hours just to find out what the README.txt is trying to tell me. I mean I just want to install it with some simple commands. When the terminal is telling me "bla bla bla not found" it's very frustrating and annoying. Can we do the installation process in a way it is just working out of the box without changing and core files?

**Comment by jeffreyvr** [comment]
Really nice attitude @rowphant

**Comment by rowphant** [comment]
@jeffreyvr Excuse my harsh comment. I was in a hurry and just wanted to quickly set up and test the theme because a client wanted me to. Though I am wondering why there seems to be no solution neither in the readme nor in the stackoverflow thread. But finally i got it working by asking chatgpt:

Just type the following command in the bash:
`export PATH="$HOME/.composer/vendor/bin:$PATH"`

Now the theme is working good but im still wondering why I have to define a path just for installing a wordpress theme. ;)

Thanks for your work and for creating tailpress. 💚

**Comment by jeffreyvr** [comment]
Thanks @rowphant. Just to be clear, the installer is totally optional. You can also just clone the repo and go from there, as described here:

https://github.com/jeffreyvr/tailpress?tab=readme-ov-file#regular-method

But If you're gonna do more themes, the installer will come in handy.

I did document setting up the path: 
https://github.com/jeffreyvr/tailpress?tab=readme-ov-file#command-tailpress-not-found

which is referenced here: https://github.com/jeffreyvr/tailpress?tab=readme-ov-file#using-the-installer
