### ISSUE TITLE
Browsersync does'nt open proxy link?

### ISSUE THREAD

**Issue by Loosie94** [jeffreyvr/tailpress#56]
Hi,

Really like your project but the script: npm run watch-sync, does not seem to open the given proxy link.
When I try it, it opens: localhost:3000 instead of tailwind.test:3000 (I'm using Laravel Valet).

Any idea how to fix this? Thanks!

**Comment by jeffreyvr** [comment]
You must change the domain in `package.json`:

https://github.com/jeffreyvr/tailpress/blob/master/package.json#L27

Will see if I can automate this in the future or add a note in the readme.

**Comment by ethanmay** [comment]
For any future readers, I was having a proxy issue using my own local php setup. Setting the proxy to `127.0.0.1` rather than `localhost` solved my problem. I also removed the "host" property from the command.

**Comment by n1smo** [comment]
> Setting the proxy to `127.0.0.1` rather than `localhost` solved my problem.

That worked, thx

**Comment by Loosie94** [comment]
Unfortunately still not working for me. Getting: ERR_CONNECTION_REFUSED
Tested @ethanmay 's answer

**Comment by jeffreyvr** [comment]
@Loosie94 I don't think this is an issue with TailPress specifically, that's why I closed the issue. I can't reproduce the error you are describing.

Just to be sure I tested it again with a fresh theme (and I'm using Laravel Valet):

https://user-images.githubusercontent.com/9550079/152531679-5d1a2cb6-baed-44fc-bbd6-27effcfc772b.mov
